# Generated by Django 2.2.3 on 2019-07-22 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app', '0002_travel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='travel',
            old_name='title',
            new_name='place',
        ),
    ]
